name: Deploy Nginx

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
#        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#        export_default_credentials: true
      
    - name: build and push the docker image
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev
        docker buildx build --platform linux/amd64 -t europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/guild-open-tech-repository/got-web-front:latest .
        docker push europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/guild-open-tech-repository/got-web-front:latest
