name: Deploy got-web-front

on:
  push:
    branches:
       - main
       - develop

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Guildopentech      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
#        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#        export_default_credentials: true
      
    - name: build and push the docker image
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker buildx build --platform linux/amd64 -t europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/guild-open-tech-repository/got-web-front:latest .
        docker push europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/guild-open-tech-repository/got-web-front:latest
